name: sync-zzuClock

on:
  push:
    branches:
      -master
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *   # 每天0点自动同步
  watch:                                                        # 监视操作
    types: [started]                                            # 点击 Star 之后
jobs:
  update_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }} # 令牌
          upstream_repository: s123456-max/zzuClock  # 上游仓库
          target_repository: AlecMaxPro/zzuClock  # 你要推送的仓库
          upstream_branch: master  # 默认是拉取上游仓库的master分支
          target_branch: master  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
